### ISSUE TITLE
Crash on INF Selector when ran from Auto Installer

### ISSUE THREAD

**Issue by alanbradleyy** [futuretechlab/BravoPrinterEfficiencyTool#3]
When running BPET for the first time after extracting on the designated workstation, BPET crashes after clicking the "Choose" button for the .INF file selector.

To replicate, rerun the extractor for the .zip file and let that open BPET as opposed to opening BPET manually. I believe that the problem is caused due to the program not being ran as an Administrator through the installer.

![image](https://user-images.githubusercontent.com/33699912/32854234-d10523b0-c9f2-11e7-9e89-d8d569007c0a.png)

**Comment by futuretechlab** [comment]
This bug is likely due to a relative path issue. When the app is launched from the exe, the choose button works just fine. I tried launching the app from the command line, and sure enough, the program still crashed when I tried to open the driver chooser. It seems to be a "working directory" issue. I have updated the relative path logic for INF discovery and well see if this clears the bug.

**Comment by futuretechlab** [comment]
I've cleared the bug and released v1.1
